# Generated by Django 4.2 on 2023-05-12 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Business ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('Lodging', 'Lodging'), ('Restaurants', 'Restaurants'), ('Things To Do', 'Things to do')], default='Things To Do', max_length=12)),
                ('pricerange', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_name', models.CharField(max_length=255)),
                ('itinerary_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Itinerary ID')),
                ('business_list', models.ManyToManyField(to='members.business')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
