# Generated by Django 4.2 on 2023-05-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Location ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Itinerary ID')),
                ('travel_time', models.DateTimeField()),
                ('location_list', models.ManyToManyField(to='members.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Business ID')),
                ('business_name', models.CharField(max_length=255)),
                ('pricerange', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.location')),
            ],
        ),
    ]
